env:
  browser: true
  es6: true
  jest: true
extends:
  - 'eslint:recommended'
  - 'plugin:flowtype/recommended'
  - 'plugin:react/recommended'
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
  - flowtype
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  flowtype/semi:
    - error
