// flow-typed signature: 85a221993252b110df5db132ce797372
// flow-typed version: <<STUB>>/react-gif-player_v^0.2.2/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-gif-player'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-gif-player' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-gif-player/devServer' {
  declare module.exports: any;
}

declare module 'react-gif-player/dist/gifplayer' {
  declare module.exports: any;
}

declare module 'react-gif-player/src/GifPlayer' {
  declare module.exports: any;
}

declare module 'react-gif-player/src/index' {
  declare module.exports: any;
}

declare module 'react-gif-player/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-gif-player/devServer.js' {
  declare module.exports: $Exports<'react-gif-player/devServer'>;
}
declare module 'react-gif-player/dist/gifplayer.js' {
  declare module.exports: $Exports<'react-gif-player/dist/gifplayer'>;
}
declare module 'react-gif-player/src/GifPlayer.js' {
  declare module.exports: $Exports<'react-gif-player/src/GifPlayer'>;
}
declare module 'react-gif-player/src/index.js' {
  declare module.exports: $Exports<'react-gif-player/src/index'>;
}
declare module 'react-gif-player/webpack.config.js' {
  declare module.exports: $Exports<'react-gif-player/webpack.config'>;
}
