// flow-typed signature: 5d3b39c0cf3f562378e93b6c8e388dce
// flow-typed version: <<STUB>>/rss-parser_v^2.6.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rss-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rss-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rss-parser/dist/rss-parser' {
  declare module.exports: any;
}

declare module 'rss-parser/dist/rss-parser.min' {
  declare module.exports: any;
}

declare module 'rss-parser/Gruntfile' {
  declare module.exports: any;
}

declare module 'rss-parser/test/parser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rss-parser/dist/rss-parser.js' {
  declare module.exports: $Exports<'rss-parser/dist/rss-parser'>;
}
declare module 'rss-parser/dist/rss-parser.min.js' {
  declare module.exports: $Exports<'rss-parser/dist/rss-parser.min'>;
}
declare module 'rss-parser/Gruntfile.js' {
  declare module.exports: $Exports<'rss-parser/Gruntfile'>;
}
declare module 'rss-parser/index' {
  declare module.exports: $Exports<'rss-parser'>;
}
declare module 'rss-parser/index.js' {
  declare module.exports: $Exports<'rss-parser'>;
}
declare module 'rss-parser/test/parser.js' {
  declare module.exports: $Exports<'rss-parser/test/parser'>;
}
