// flow-typed signature: 3b113238a8eb933912ec63482d75a8fb
// flow-typed version: <<STUB>>/smooch_v^3.14.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'smooch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'smooch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'smooch/lib/actions/app-actions' {
  declare module.exports: any;
}

declare module 'smooch/lib/actions/app-state-actions' {
  declare module.exports: any;
}

declare module 'smooch/lib/actions/auth-actions' {
  declare module.exports: any;
}

declare module 'smooch/lib/actions/browser-actions' {
  declare module.exports: any;
}

declare module 'smooch/lib/actions/common-actions' {
  declare module.exports: any;
}

declare module 'smooch/lib/actions/conversation-actions' {
  declare module.exports: any;
}

declare module 'smooch/lib/actions/faye-actions' {
  declare module.exports: any;
}

declare module 'smooch/lib/actions/integrations-actions' {
  declare module.exports: any;
}

declare module 'smooch/lib/actions/ui-actions' {
  declare module.exports: any;
}

declare module 'smooch/lib/actions/user-actions' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/action' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/alternate-channels' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/channels/channel-page' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/channels/channel' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/channels/email-channel-content' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/channels/line-channel-content' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/channels/messenger-channel-content' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/channels/telegram-channel-content' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/channels/transfer-request-channel-content' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/channels/twilio-channel-content' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/channels/viber-channel-content' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/channels/wechat-channel-content' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/chat-input' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/connect-notification' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/conversation' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/default-app-icon' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/default-button-icon' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/email-settings' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/error-notification' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/header' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/image-loading' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/image-message' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/image-upload' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/introduction' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/loading' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/location-icon' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/message-indicator' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/message' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/messenger-button' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/notification-channel-item' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/notifications-settings' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/reply-actions' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/settings' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/text-message' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/typing-indicator' {
  declare module.exports: any;
}

declare module 'smooch/lib/components/widget' {
  declare module.exports: any;
}

declare module 'smooch/lib/constants/app' {
  declare module.exports: any;
}

declare module 'smooch/lib/constants/assets' {
  declare module.exports: any;
}

declare module 'smooch/lib/constants/channels' {
  declare module.exports: any;
}

declare module 'smooch/lib/constants/country-data' {
  declare module.exports: any;
}

declare module 'smooch/lib/constants/message' {
  declare module.exports: any;
}

declare module 'smooch/lib/constants/notifications' {
  declare module.exports: any;
}

declare module 'smooch/lib/constants/styles' {
  declare module.exports: any;
}

declare module 'smooch/lib/constants/version' {
  declare module.exports: any;
}

declare module 'smooch/lib/lib/blueimp-load-image/load-image-exif-map' {
  declare module.exports: any;
}

declare module 'smooch/lib/lib/blueimp-load-image/load-image-exif' {
  declare module.exports: any;
}

declare module 'smooch/lib/lib/blueimp-load-image/load-image-meta' {
  declare module.exports: any;
}

declare module 'smooch/lib/lib/blueimp-load-image/load-image-orientation' {
  declare module.exports: any;
}

declare module 'smooch/lib/lib/blueimp-load-image/load-image' {
  declare module.exports: any;
}

declare module 'smooch/lib/lib/load-image' {
  declare module.exports: any;
}

declare module 'smooch/lib/lib/react-telephone-input' {
  declare module.exports: any;
}

declare module 'smooch/lib/main' {
  declare module.exports: any;
}

declare module 'smooch/lib/reducers/app-reducer' {
  declare module.exports: any;
}

declare module 'smooch/lib/reducers/app-state-reducer' {
  declare module.exports: any;
}

declare module 'smooch/lib/reducers/auth-reducer' {
  declare module.exports: any;
}

declare module 'smooch/lib/reducers/browser-reducer' {
  declare module.exports: any;
}

declare module 'smooch/lib/reducers/conversation-reducer' {
  declare module.exports: any;
}

declare module 'smooch/lib/reducers/faye-reducer' {
  declare module.exports: any;
}

declare module 'smooch/lib/reducers/integrations-reducer' {
  declare module.exports: any;
}

declare module 'smooch/lib/reducers/root-reducer' {
  declare module.exports: any;
}

declare module 'smooch/lib/reducers/ui-reducer' {
  declare module.exports: any;
}

declare module 'smooch/lib/reducers/user-reducer' {
  declare module.exports: any;
}

declare module 'smooch/lib/root' {
  declare module.exports: any;
}

declare module 'smooch/lib/services/app' {
  declare module.exports: any;
}

declare module 'smooch/lib/services/auth' {
  declare module.exports: any;
}

declare module 'smooch/lib/services/conversation' {
  declare module.exports: any;
}

declare module 'smooch/lib/services/core' {
  declare module.exports: any;
}

declare module 'smooch/lib/services/faye' {
  declare module.exports: any;
}

declare module 'smooch/lib/services/integrations' {
  declare module.exports: any;
}

declare module 'smooch/lib/services/stripe' {
  declare module.exports: any;
}

declare module 'smooch/lib/services/user' {
  declare module.exports: any;
}

declare module 'smooch/lib/smooch' {
  declare module.exports: any;
}

declare module 'smooch/lib/store/configure-dev' {
  declare module.exports: any;
}

declare module 'smooch/lib/store/configure-prod' {
  declare module.exports: any;
}

declare module 'smooch/lib/store/index' {
  declare module.exports: any;
}

declare module 'smooch/lib/umd' {
  declare module.exports: any;
}

declare module 'smooch/lib/utils/app' {
  declare module.exports: any;
}

declare module 'smooch/lib/utils/colors' {
  declare module.exports: any;
}

declare module 'smooch/lib/utils/css' {
  declare module.exports: any;
}

declare module 'smooch/lib/utils/device' {
  declare module.exports: any;
}

declare module 'smooch/lib/utils/dom' {
  declare module.exports: any;
}

declare module 'smooch/lib/utils/events' {
  declare module.exports: any;
}

declare module 'smooch/lib/utils/html' {
  declare module.exports: any;
}

declare module 'smooch/lib/utils/media' {
  declare module.exports: any;
}

declare module 'smooch/lib/utils/polyfills' {
  declare module.exports: any;
}

declare module 'smooch/lib/utils/sound' {
  declare module.exports: any;
}

declare module 'smooch/lib/utils/storage' {
  declare module.exports: any;
}

declare module 'smooch/lib/utils/strings' {
  declare module.exports: any;
}

declare module 'smooch/lib/utils/throttle' {
  declare module.exports: any;
}

declare module 'smooch/lib/utils/user' {
  declare module.exports: any;
}

declare module 'smooch/webpack-staging.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'smooch/lib/actions/app-actions.js' {
  declare module.exports: $Exports<'smooch/lib/actions/app-actions'>;
}
declare module 'smooch/lib/actions/app-state-actions.js' {
  declare module.exports: $Exports<'smooch/lib/actions/app-state-actions'>;
}
declare module 'smooch/lib/actions/auth-actions.js' {
  declare module.exports: $Exports<'smooch/lib/actions/auth-actions'>;
}
declare module 'smooch/lib/actions/browser-actions.js' {
  declare module.exports: $Exports<'smooch/lib/actions/browser-actions'>;
}
declare module 'smooch/lib/actions/common-actions.js' {
  declare module.exports: $Exports<'smooch/lib/actions/common-actions'>;
}
declare module 'smooch/lib/actions/conversation-actions.js' {
  declare module.exports: $Exports<'smooch/lib/actions/conversation-actions'>;
}
declare module 'smooch/lib/actions/faye-actions.js' {
  declare module.exports: $Exports<'smooch/lib/actions/faye-actions'>;
}
declare module 'smooch/lib/actions/integrations-actions.js' {
  declare module.exports: $Exports<'smooch/lib/actions/integrations-actions'>;
}
declare module 'smooch/lib/actions/ui-actions.js' {
  declare module.exports: $Exports<'smooch/lib/actions/ui-actions'>;
}
declare module 'smooch/lib/actions/user-actions.js' {
  declare module.exports: $Exports<'smooch/lib/actions/user-actions'>;
}
declare module 'smooch/lib/components/action.js' {
  declare module.exports: $Exports<'smooch/lib/components/action'>;
}
declare module 'smooch/lib/components/alternate-channels.js' {
  declare module.exports: $Exports<'smooch/lib/components/alternate-channels'>;
}
declare module 'smooch/lib/components/channels/channel-page.js' {
  declare module.exports: $Exports<'smooch/lib/components/channels/channel-page'>;
}
declare module 'smooch/lib/components/channels/channel.js' {
  declare module.exports: $Exports<'smooch/lib/components/channels/channel'>;
}
declare module 'smooch/lib/components/channels/email-channel-content.js' {
  declare module.exports: $Exports<'smooch/lib/components/channels/email-channel-content'>;
}
declare module 'smooch/lib/components/channels/line-channel-content.js' {
  declare module.exports: $Exports<'smooch/lib/components/channels/line-channel-content'>;
}
declare module 'smooch/lib/components/channels/messenger-channel-content.js' {
  declare module.exports: $Exports<'smooch/lib/components/channels/messenger-channel-content'>;
}
declare module 'smooch/lib/components/channels/telegram-channel-content.js' {
  declare module.exports: $Exports<'smooch/lib/components/channels/telegram-channel-content'>;
}
declare module 'smooch/lib/components/channels/transfer-request-channel-content.js' {
  declare module.exports: $Exports<'smooch/lib/components/channels/transfer-request-channel-content'>;
}
declare module 'smooch/lib/components/channels/twilio-channel-content.js' {
  declare module.exports: $Exports<'smooch/lib/components/channels/twilio-channel-content'>;
}
declare module 'smooch/lib/components/channels/viber-channel-content.js' {
  declare module.exports: $Exports<'smooch/lib/components/channels/viber-channel-content'>;
}
declare module 'smooch/lib/components/channels/wechat-channel-content.js' {
  declare module.exports: $Exports<'smooch/lib/components/channels/wechat-channel-content'>;
}
declare module 'smooch/lib/components/chat-input.js' {
  declare module.exports: $Exports<'smooch/lib/components/chat-input'>;
}
declare module 'smooch/lib/components/connect-notification.js' {
  declare module.exports: $Exports<'smooch/lib/components/connect-notification'>;
}
declare module 'smooch/lib/components/conversation.js' {
  declare module.exports: $Exports<'smooch/lib/components/conversation'>;
}
declare module 'smooch/lib/components/default-app-icon.js' {
  declare module.exports: $Exports<'smooch/lib/components/default-app-icon'>;
}
declare module 'smooch/lib/components/default-button-icon.js' {
  declare module.exports: $Exports<'smooch/lib/components/default-button-icon'>;
}
declare module 'smooch/lib/components/email-settings.js' {
  declare module.exports: $Exports<'smooch/lib/components/email-settings'>;
}
declare module 'smooch/lib/components/error-notification.js' {
  declare module.exports: $Exports<'smooch/lib/components/error-notification'>;
}
declare module 'smooch/lib/components/header.js' {
  declare module.exports: $Exports<'smooch/lib/components/header'>;
}
declare module 'smooch/lib/components/image-loading.js' {
  declare module.exports: $Exports<'smooch/lib/components/image-loading'>;
}
declare module 'smooch/lib/components/image-message.js' {
  declare module.exports: $Exports<'smooch/lib/components/image-message'>;
}
declare module 'smooch/lib/components/image-upload.js' {
  declare module.exports: $Exports<'smooch/lib/components/image-upload'>;
}
declare module 'smooch/lib/components/introduction.js' {
  declare module.exports: $Exports<'smooch/lib/components/introduction'>;
}
declare module 'smooch/lib/components/loading.js' {
  declare module.exports: $Exports<'smooch/lib/components/loading'>;
}
declare module 'smooch/lib/components/location-icon.js' {
  declare module.exports: $Exports<'smooch/lib/components/location-icon'>;
}
declare module 'smooch/lib/components/message-indicator.js' {
  declare module.exports: $Exports<'smooch/lib/components/message-indicator'>;
}
declare module 'smooch/lib/components/message.js' {
  declare module.exports: $Exports<'smooch/lib/components/message'>;
}
declare module 'smooch/lib/components/messenger-button.js' {
  declare module.exports: $Exports<'smooch/lib/components/messenger-button'>;
}
declare module 'smooch/lib/components/notification-channel-item.js' {
  declare module.exports: $Exports<'smooch/lib/components/notification-channel-item'>;
}
declare module 'smooch/lib/components/notifications-settings.js' {
  declare module.exports: $Exports<'smooch/lib/components/notifications-settings'>;
}
declare module 'smooch/lib/components/reply-actions.js' {
  declare module.exports: $Exports<'smooch/lib/components/reply-actions'>;
}
declare module 'smooch/lib/components/settings.js' {
  declare module.exports: $Exports<'smooch/lib/components/settings'>;
}
declare module 'smooch/lib/components/text-message.js' {
  declare module.exports: $Exports<'smooch/lib/components/text-message'>;
}
declare module 'smooch/lib/components/typing-indicator.js' {
  declare module.exports: $Exports<'smooch/lib/components/typing-indicator'>;
}
declare module 'smooch/lib/components/widget.js' {
  declare module.exports: $Exports<'smooch/lib/components/widget'>;
}
declare module 'smooch/lib/constants/app.js' {
  declare module.exports: $Exports<'smooch/lib/constants/app'>;
}
declare module 'smooch/lib/constants/assets.js' {
  declare module.exports: $Exports<'smooch/lib/constants/assets'>;
}
declare module 'smooch/lib/constants/channels.js' {
  declare module.exports: $Exports<'smooch/lib/constants/channels'>;
}
declare module 'smooch/lib/constants/country-data.js' {
  declare module.exports: $Exports<'smooch/lib/constants/country-data'>;
}
declare module 'smooch/lib/constants/message.js' {
  declare module.exports: $Exports<'smooch/lib/constants/message'>;
}
declare module 'smooch/lib/constants/notifications.js' {
  declare module.exports: $Exports<'smooch/lib/constants/notifications'>;
}
declare module 'smooch/lib/constants/styles.js' {
  declare module.exports: $Exports<'smooch/lib/constants/styles'>;
}
declare module 'smooch/lib/constants/version.js' {
  declare module.exports: $Exports<'smooch/lib/constants/version'>;
}
declare module 'smooch/lib/lib/blueimp-load-image/load-image-exif-map.js' {
  declare module.exports: $Exports<'smooch/lib/lib/blueimp-load-image/load-image-exif-map'>;
}
declare module 'smooch/lib/lib/blueimp-load-image/load-image-exif.js' {
  declare module.exports: $Exports<'smooch/lib/lib/blueimp-load-image/load-image-exif'>;
}
declare module 'smooch/lib/lib/blueimp-load-image/load-image-meta.js' {
  declare module.exports: $Exports<'smooch/lib/lib/blueimp-load-image/load-image-meta'>;
}
declare module 'smooch/lib/lib/blueimp-load-image/load-image-orientation.js' {
  declare module.exports: $Exports<'smooch/lib/lib/blueimp-load-image/load-image-orientation'>;
}
declare module 'smooch/lib/lib/blueimp-load-image/load-image.js' {
  declare module.exports: $Exports<'smooch/lib/lib/blueimp-load-image/load-image'>;
}
declare module 'smooch/lib/lib/load-image.js' {
  declare module.exports: $Exports<'smooch/lib/lib/load-image'>;
}
declare module 'smooch/lib/lib/react-telephone-input.js' {
  declare module.exports: $Exports<'smooch/lib/lib/react-telephone-input'>;
}
declare module 'smooch/lib/main.js' {
  declare module.exports: $Exports<'smooch/lib/main'>;
}
declare module 'smooch/lib/reducers/app-reducer.js' {
  declare module.exports: $Exports<'smooch/lib/reducers/app-reducer'>;
}
declare module 'smooch/lib/reducers/app-state-reducer.js' {
  declare module.exports: $Exports<'smooch/lib/reducers/app-state-reducer'>;
}
declare module 'smooch/lib/reducers/auth-reducer.js' {
  declare module.exports: $Exports<'smooch/lib/reducers/auth-reducer'>;
}
declare module 'smooch/lib/reducers/browser-reducer.js' {
  declare module.exports: $Exports<'smooch/lib/reducers/browser-reducer'>;
}
declare module 'smooch/lib/reducers/conversation-reducer.js' {
  declare module.exports: $Exports<'smooch/lib/reducers/conversation-reducer'>;
}
declare module 'smooch/lib/reducers/faye-reducer.js' {
  declare module.exports: $Exports<'smooch/lib/reducers/faye-reducer'>;
}
declare module 'smooch/lib/reducers/integrations-reducer.js' {
  declare module.exports: $Exports<'smooch/lib/reducers/integrations-reducer'>;
}
declare module 'smooch/lib/reducers/root-reducer.js' {
  declare module.exports: $Exports<'smooch/lib/reducers/root-reducer'>;
}
declare module 'smooch/lib/reducers/ui-reducer.js' {
  declare module.exports: $Exports<'smooch/lib/reducers/ui-reducer'>;
}
declare module 'smooch/lib/reducers/user-reducer.js' {
  declare module.exports: $Exports<'smooch/lib/reducers/user-reducer'>;
}
declare module 'smooch/lib/root.js' {
  declare module.exports: $Exports<'smooch/lib/root'>;
}
declare module 'smooch/lib/services/app.js' {
  declare module.exports: $Exports<'smooch/lib/services/app'>;
}
declare module 'smooch/lib/services/auth.js' {
  declare module.exports: $Exports<'smooch/lib/services/auth'>;
}
declare module 'smooch/lib/services/conversation.js' {
  declare module.exports: $Exports<'smooch/lib/services/conversation'>;
}
declare module 'smooch/lib/services/core.js' {
  declare module.exports: $Exports<'smooch/lib/services/core'>;
}
declare module 'smooch/lib/services/faye.js' {
  declare module.exports: $Exports<'smooch/lib/services/faye'>;
}
declare module 'smooch/lib/services/integrations.js' {
  declare module.exports: $Exports<'smooch/lib/services/integrations'>;
}
declare module 'smooch/lib/services/stripe.js' {
  declare module.exports: $Exports<'smooch/lib/services/stripe'>;
}
declare module 'smooch/lib/services/user.js' {
  declare module.exports: $Exports<'smooch/lib/services/user'>;
}
declare module 'smooch/lib/smooch.js' {
  declare module.exports: $Exports<'smooch/lib/smooch'>;
}
declare module 'smooch/lib/store/configure-dev.js' {
  declare module.exports: $Exports<'smooch/lib/store/configure-dev'>;
}
declare module 'smooch/lib/store/configure-prod.js' {
  declare module.exports: $Exports<'smooch/lib/store/configure-prod'>;
}
declare module 'smooch/lib/store/index.js' {
  declare module.exports: $Exports<'smooch/lib/store/index'>;
}
declare module 'smooch/lib/umd.js' {
  declare module.exports: $Exports<'smooch/lib/umd'>;
}
declare module 'smooch/lib/utils/app.js' {
  declare module.exports: $Exports<'smooch/lib/utils/app'>;
}
declare module 'smooch/lib/utils/colors.js' {
  declare module.exports: $Exports<'smooch/lib/utils/colors'>;
}
declare module 'smooch/lib/utils/css.js' {
  declare module.exports: $Exports<'smooch/lib/utils/css'>;
}
declare module 'smooch/lib/utils/device.js' {
  declare module.exports: $Exports<'smooch/lib/utils/device'>;
}
declare module 'smooch/lib/utils/dom.js' {
  declare module.exports: $Exports<'smooch/lib/utils/dom'>;
}
declare module 'smooch/lib/utils/events.js' {
  declare module.exports: $Exports<'smooch/lib/utils/events'>;
}
declare module 'smooch/lib/utils/html.js' {
  declare module.exports: $Exports<'smooch/lib/utils/html'>;
}
declare module 'smooch/lib/utils/media.js' {
  declare module.exports: $Exports<'smooch/lib/utils/media'>;
}
declare module 'smooch/lib/utils/polyfills.js' {
  declare module.exports: $Exports<'smooch/lib/utils/polyfills'>;
}
declare module 'smooch/lib/utils/sound.js' {
  declare module.exports: $Exports<'smooch/lib/utils/sound'>;
}
declare module 'smooch/lib/utils/storage.js' {
  declare module.exports: $Exports<'smooch/lib/utils/storage'>;
}
declare module 'smooch/lib/utils/strings.js' {
  declare module.exports: $Exports<'smooch/lib/utils/strings'>;
}
declare module 'smooch/lib/utils/throttle.js' {
  declare module.exports: $Exports<'smooch/lib/utils/throttle'>;
}
declare module 'smooch/lib/utils/user.js' {
  declare module.exports: $Exports<'smooch/lib/utils/user'>;
}
declare module 'smooch/webpack-staging.config.js' {
  declare module.exports: $Exports<'smooch/webpack-staging.config'>;
}
